# Generated by Django 4.0.4 on 2022-06-23 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_rename_updted_room_updated_message_room_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='updated',
            new_name='updted',
        ),
        migrations.RemoveField(
            model_name='room',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
